# numpy

In [ ]:
# list and array difference(2)
array = [
    [1,2],
    [1,2]
]

In [2]:
import numpy as np

In [3]:
# creating numpy array
l = [1,2,3,4,5,6]
x = np.array(l)
print(l,x,type(l),type(x))

[1, 2, 3, 4, 5, 6] [1 2 3 4 5 6] <class 'list'> <class 'numpy.ndarray'>


In [4]:
l = [
    [1,2],
    [3,4]
]
x = np.array(l)
print(x)

[[1 2]
 [3 4]]


In [9]:
print(np.zeros((2,4)))
print(np.ones((5,6)))
print(np.random.randint(3,100))
print(np.random.rand(3,4))
print(np.arange(8))
x = np.arange(1,8)
#x = x[:]
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
49
[[0.1263323  0.79159949 0.02772408 0.24964659]
 [0.00290753 0.22066014 0.20271416 0.04401436]
 [0.47766879 0.41800911 0.83698641 0.39099015]]
[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [14]:
# math operations(dimensions should match)
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)
print(x+y) # or use np.add
print(x-y)
print(x*y) # elementwise
print(np.dot(x,y)) #matrix multipy
print(x/y)
print(x**y)
print(np.array()*x,'lllllllllll')
2 * x
[1,5,10] * x
[
    [1,5,10], * x
    [1,5,10]
]


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[    1    64]
 [ 2187 65536]]


ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [15]:
# linalg

x = np.array([[1,2],[3,4]])
print(np.linalg.matrix_rank(x))
print(np.linalg.eig(x))
print(np.linalg.eigvals(x))

2
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
[-0.37228132  5.37228132]


In [39]:
# reshape, shape, size
x = np.array([[1,2,3,4,3,4,5,4],[1,2,3,4,3,4,5,4]])
print(x.shape,x)
x = x.reshape((4,4))
print(x.shape,x)
print(x.size)

(2, 8) [[1 2 3 4 3 4 5 4]
 [1 2 3 4 3 4 5 4]]
(4, 4) [[1 2 3 4]
 [3 4 5 4]
 [1 2 3 4]
 [3 4 5 4]]
16
